input {
	beats {
		port => 5044
	}

	tcp {
		port => 5000
	}
}

## Add your filters / logstash plugins configuration here
filter {
	#if [type] == "nginx-access" {
		grok {
			match => {
					"message" => [ '(.*) "%{IP:remote_addr}"' ]
			}
		}
		#if [remote_addr] != null {
			geoip { 
				source => "remote_addr"
			}
		#}
	#}
}

output {
	elasticsearch {
		hosts => "elasticsearch:9200"
		user => "elastic"
		password => "changeme"
		ecs_compatibility => disabled
	}
}
